#!/usr/bin/env python3
"""Check the show magazine's exhibitor index against data.js and save it as magazine/exhibitors.json.

The index (room, exhibitor, page) is printed in the DAE show magazine. Photograph it, put the photos in
magazine/, and type or paste the rows into magazine/list.txt, one per line as printed:

    36 ACM PREMIUM AUDIO P. 19
    GLAZEN FOYER MUSIC EMOTION            (no page)

Blank lines and lines starting with # are skipped, and a row that is in the file twice (overlapping
photos) counts once. OCR output works too ("p 19", "p.19"); misread names are matched to the nearest
data.js exhibitor and reported, so check those. Then run:

    python 2026/sourcedata/build_magazine.py [list.txt ...]

It writes magazine/exhibitors.json ([{room, exhibitor, ex, page}]: room as data.js names it, exhibitor
as printed, ex = EX key in data.js or null), replaces the MAG_PAGE block at the end of ../data.js (room ->
exhibitor -> page, shown as a badge in the room tooltip) and lists every difference with data.js: rooms
that don't match, exhibitors on one side only, rows without a page. A magazine name that has no data.js exhibitor
under the same name goes in ALIAS.
Python 3, standard library only.
"""
import difflib
import json
import re
import sys
from pathlib import Path

from build_hifi import load_data_js, norm

HERE = Path(__file__).resolve().parent
MAG = HERE / "magazine"
DATA_JS = HERE.parent / "data.js"
MAG_JS = "// Room -> exhibitor -> page in the show magazine."  # first line of the generated block in data.js

# Magazine name -> EX key in data.js, where the plain name doesn't match.
ALIAS = {
    "AF GROUP": "AF Group SRL",
    "HORN-KULTUR": "horn-kultur / STUdo-Hifi",
    "STUDO-HIFI": "horn-kultur / STUdo-Hifi",
    "ISOACOUSTICS NEDERLAND": "IsoAcoustics",
    "JS WOOD & SOUND": "Joep Slooten speakers & meubels",
    "STS - DIGITAL": "STS Analog / STS Digital",
}
ROOM = re.compile(r"^(\d+|[A-Za-z]+ foyer|[A-Za-z]+zaal|galerij)\s+(.*)$", re.I)
PAGE = re.compile(r"\s+p\s*\.?\s*(\d+)$", re.I)


def parse(line):
    """'36 ACM PREMIUM AUDIO P. 19' -> ('36', 'ACM PREMIUM AUDIO', 19); None if there is no room."""
    line = " ".join(line.split())
    page = PAGE.search(line)
    if page:
        line = line[: page.start()]
    m = ROOM.match(line)
    if not m:
        return None
    return m.group(1), m.group(2), int(page.group(1)) if page else None


def read_rows(paths):
    rows, bad = [], []
    for path in paths:
        for n, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            row = parse(line)
            if row is None:
                bad.append(f"{path}:{n}: no room at the start: {line.strip()!r}")
            elif row not in rows:
                rows.append(row)
    return rows, bad


def match_room(room, rooms):
    """Magazine room -> OCCUPANTS key: 'HOLLAND FOYER' -> 'Holland foyer (Headspace)'."""
    if room.isdigit():
        return room
    hits = [r for r in rooms if r.lower().startswith(room.lower())]
    return hits[0] if len(hits) == 1 else room.capitalize()


def match_exhibitor(name, by_norm):
    """Magazine name -> (EX key or None, True when it was a fuzzy guess)."""
    if name in ALIAS:
        return ALIAS[name], False
    if norm(name) in by_norm:
        return by_norm[norm(name)], False
    close = difflib.get_close_matches(norm(name), list(by_norm), n=1, cutoff=0.8)
    return (by_norm[close[0]], True) if close else (None, False)


def write_data_js(out, where):
    """Replace (or append) the MAG_PAGE block at the end of data.js: only rows data.js agrees with."""
    pages = {}
    for o in out:
        if o["ex"] and o["page"] and o["room"] in where.get(o["ex"], []):
            pages.setdefault(o["room"], {})[o["ex"]] = o["page"]
    block = "\n".join([
        MAG_JS + " Generated by sourcedata/build_magazine.py from sourcedata/magazine/list.txt; edit that, not this.",
        "const MAG_PAGE = {",
        ",\n".join(json.dumps(r, ensure_ascii=False) + ":" + json.dumps(p, ensure_ascii=False) for r, p in pages.items()),
        "};",
        "",
    ])
    src = DATA_JS.read_text(encoding="utf-8")
    src = src.split("\n" + MAG_JS, 1)[0].rstrip("\n") + "\n\n" + block
    DATA_JS.write_text(src, encoding="utf-8")
    return sum(len(p) for p in pages.values())


def main():
    paths = sys.argv[1:] or [MAG / "list.txt"]
    rows, bad = read_rows(paths)
    if bad:
        sys.exit("\n".join(bad))
    ex, where = load_data_js()
    by_norm = {norm(e): e for e in ex}
    rooms = {r for rs in where.values() for r in rs}

    out, report = [], {"guessed": [], "unknown exhibitor": [], "unknown room": [], "other room": [], "no page": []}
    for room, name, page in rows:
        key, guessed = match_exhibitor(name, by_norm)
        room = match_room(room, rooms)
        out.append({"room": room, "exhibitor": name, "ex": key, "page": page})
        label = f"{name} | {room} | p. {page}"
        if guessed:
            report["guessed"].append(f"{label}: read as {key!r}, check the spelling or add it to ALIAS")
        if key is None:
            report["unknown exhibitor"].append(f"{label}: not in data.js")
        if room not in rooms:
            report["unknown room"].append(f"{label}: room not used in data.js")
        elif key and room not in where.get(key, []):
            report["other room"].append(f"{label}: data.js has {key!r} in {', '.join(where.get(key, [])) or 'no room'}")
        if page is None:
            report["no page"].append(label)
    seen = {(o["ex"], o["room"]) for o in out}
    report["missing from magazine"] = [
        f"{e} | {r}" for e in ex for r in where.get(e, []) if (e, r) not in seen
    ]

    (MAG / "exhibitors.json").write_text(
        "[\n" + ",\n".join(json.dumps(o, ensure_ascii=False) for o in out) + "\n]\n", encoding="utf-8"
    )
    print(f"magazine/exhibitors.json: {len(out)} rows, {len({o['ex'] for o in out if o['ex']})} exhibitors")
    print(f"data.js MAG_PAGE: {write_data_js(out, where)} pages")
    for title, lines in report.items():
        if lines:
            print(f"\n{title} ({len(lines)}):")
            print("\n".join("  " + x for x in lines))


if __name__ == "__main__":
    main()
